from __future__ import annotations

import os
from itertools import cycle

from flask import current_app

from app.extensions import db
from app.models import ToolCatalog, User


IMPLEMENTED_TOOLS = [
    {
        "tool_key": "merge_pdf",
        "name": "Merge PDF",
        "category": "Organize",
        "description": "Join multiple PDFs into one. Free up to 3 files.",
        "price_paise": 0,
        "icon_name": "bi-files",
        "template_name": "tool_pages/merge.html",
        "keywords": "merge batch combine pdf image merge",
    },
    {
        "tool_key": "split_pdf",
        "name": "Split PDF",
        "category": "Organize",
        "description": "Separate specific pages from a large PDF.",
        "price_paise": 500,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-scissors",
        "template_name": "tool_pages/split.html",
        "keywords": "split range extract pages",
    },
    {
        "tool_key": "rotate_pdf",
        "name": "Rotate Pages",
        "category": "Organize",
        "description": "Rotate selected pages to the desired orientation.",
        "price_paise": 500,
        "icon_name": "bi-arrow-repeat",
        "template_name": "tool_pages/rotate.html",
        "keywords": "rotate orientation pages",
    },
    {
        "tool_key": "delete_pages",
        "name": "Delete Pages",
        "category": "Edit",
        "description": "Remove unwanted pages from a PDF.",
        "price_paise": 500,
        "icon_name": "bi-trash3",
        "template_name": "tool_pages/delete.html",
        "keywords": "delete pages remove",
    },
    {
        "tool_key": "reorder_pdf",
        "name": "Reorder Pages",
        "category": "Organize",
        "description": "Change page order using a custom sequence.",
        "price_paise": 600,
        "icon_name": "bi-layout-sidebar-inset",
        "template_name": "tool_pages/reorder.html",
        "keywords": "reorder sequence pages",
    },
    {
        "tool_key": "watermark_pdf",
        "name": "Watermark PDF",
        "category": "Edit",
        "description": "Add custom text or images to prevent copying.",
        "price_paise": 700,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-droplet-half",
        "template_name": "tool_pages/watermark.html",
        "keywords": "watermark opacity batch stamp",
    },
    {
        "tool_key": "secure_pdf",
        "name": "Secure PDF",
        "category": "Security",
        "description": "Add or remove password protection from PDFs.",
        "price_paise": 700,
        "icon_name": "bi-shield-lock",
        "template_name": "tool_pages/security.html",
        "keywords": "password protect unlock",
    },
    {
        "tool_key": "pdf_to_images",
        "name": "PDF to Images",
        "category": "Convert",
        "description": "Export PDF pages as PNG or JPEG images.",
        "price_paise": 500,
        "icon_name": "bi-images",
        "template_name": "tool_pages/pdf_to_images.html",
        "keywords": "pdf images export",
    },
    {
        "tool_key": "images_to_pdf",
        "name": "Images to PDF",
        "category": "Convert",
        "description": "Convert photos/scans into PDF documents.",
        "price_paise": 0,
        "icon_name": "bi-file-earmark-image",
        "template_name": "tool_pages/images_to_pdf.html",
        "keywords": "images convert scan",
    },
    {
        "tool_key": "pdf_to_text",
        "name": "PDF to Text",
        "category": "Convert",
        "description": "Extract readable text from digital PDFs.",
        "price_paise": 500,
        "icon_name": "bi-file-earmark-text",
        "template_name": "tool_pages/pdf_to_text.html",
        "keywords": "extract text txt",
    },
    {
        "tool_key": "page_numbers",
        "name": "Page Number Generator",
        "category": "Utilities",
        "description": "Add page numbers with placement and font-size controls.",
        "price_paise": 500,
        "icon_name": "bi-123",
        "template_name": "tool_pages/page_numbers.html",
        "keywords": "page number footer header",
    },
    {
        "tool_key": "header_footer",
        "name": "Header/Footer",
        "category": "Utilities",
        "description": "Apply document headers and footers across all pages.",
        "price_paise": 600,
        "icon_name": "bi-text-paragraph",
        "template_name": "tool_pages/header_footer.html",
        "keywords": "header footer text",
    },
    {
        "tool_key": "remove_metadata",
        "name": "Remove Metadata",
        "category": "Utilities",
        "description": "Strip PDF metadata for cleaner document sharing.",
        "price_paise": 500,
        "icon_name": "bi-incognito",
        "template_name": "tool_pages/remove_metadata.html",
        "keywords": "metadata privacy clean",
    },
    {
        "tool_key": "document_scanner",
        "name": "Document Scanner",
        "category": "Office",
        "description": "Scan images into enhanced PDFs with crop and black-and-white modes.",
        "price_paise": 700,
        "icon_name": "bi-camera",
        "template_name": "tool_pages/scanner.html",
        "keywords": "scan camera crop enhance",
    },
    {
        "tool_key": "digital_signature",
        "name": "Digital Signatures",
        "category": "Office",
        "description": "Draw or upload signatures and place them on PDF pages.",
        "price_paise": 800,
        "icon_name": "bi-pen",
        "template_name": "tool_pages/signature.html",
        "keywords": "signature sign hr office",
    },
    {
        "tool_key": "compress_pdf",
        "name": "Compress PDF",
        "category": "Utilities",
        "description": "Reduce PDF file size using low, balanced, or strong compression.",
        "price_paise": 600,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-file-zip",
        "template_name": "tool_pages/compress.html",
        "keywords": "compress size reduction",
    },
    {
        "tool_key": "pdf_to_word",
        "name": "PDF to Word",
        "category": "Convert",
        "description": "Convert PDF into editable Word documents.",
        "price_paise": 1000,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-file-earmark-word",
        "template_name": "tool_pages/office_convert.html",
        "keywords": "word docx office editable",
    },
    {
        "tool_key": "pdf_to_ppt",
        "name": "PDF to PowerPoint",
        "category": "Convert",
        "description": "Turn PDFs into presentation-ready PPTX slides.",
        "price_paise": 1200,
        "icon_name": "bi-file-earmark-slides",
        "template_name": "tool_pages/office_convert.html",
        "keywords": "ppt powerpoint slides office",
    },
    {
        "tool_key": "pdf_to_excel",
        "name": "PDF to Excel",
        "category": "Convert",
        "description": "Extract tables and text into Excel worksheets.",
        "price_paise": 1200,
        "icon_name": "bi-file-earmark-excel",
        "template_name": "tool_pages/office_convert.html",
        "keywords": "excel xlsx tables office",
    },
    {
        "tool_key": "image_utilities",
        "name": "Image Utilities",
        "category": "Utilities",
        "description": "Resize, compress, convert formats, and package images as PDFs.",
        "price_paise": 500,
        "icon_name": "bi-image",
        "template_name": "tool_pages/image_utilities.html",
        "keywords": "resize convert compress image pdf",
    },
    {
        "tool_key": "file_share",
        "name": "Secure File Share",
        "category": "Office",
        "description": "Generate protected share links with expiry timers and passwords.",
        "price_paise": 500,
        "icon_name": "bi-share",
        "template_name": "tool_pages/share.html",
        "keywords": "share link password expiry",
    },
    {
        "tool_key": "cloud_storage",
        "name": "Cloud Storage",
        "category": "Office",
        "description": "Store, rename, preview, and manage personal productivity files.",
        "price_paise": 0,
        "icon_name": "bi-cloud",
        "template_name": "tool_pages/cloud_storage.html",
        "keywords": "cloud upload preview files",
    },
    {
        "tool_key": "ocr_pdf",
        "name": "OCR Scanner",
        "category": "OCR",
        "description": "Extract text from images or scanned PDFs.",
        "price_paise": 1500,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-binoculars",
        "template_name": "tool_pages/ocr.html",
        "keywords": "ocr searchable pdf",
    },
    {
        "tool_key": "student_mode",
        "name": "Student Mode",
        "category": "Students",
        "description": "Generate summaries, flashcards, quizzes, and note extracts from PDFs.",
        "price_paise": 1500,
        "icon_name": "bi-mortarboard",
        "template_name": "tool_pages/student_mode.html",
        "keywords": "study flashcards summary quiz",
    },
    {
        "tool_key": "study_pack_pro",
        "name": "Student Study Pack Pro",
        "category": "Students",
        "description": "Generate summary, notes, flashcards, quizzes, formula sheet, and revision plan in one run.",
        "price_paise": 1800,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-journal-richtext",
        "template_name": "tool_pages/study_pack_pro.html",
        "keywords": "study pack revision formula flashcards quiz students",
    },
    {
        "tool_key": "teacher_toolkit",
        "name": "Teacher Toolkit",
        "category": "Students",
        "description": "Build question paper, answer key, rubric, and lesson plan from source material.",
        "price_paise": 2200,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-easel2",
        "template_name": "tool_pages/teacher_toolkit.html",
        "keywords": "teacher exam question paper answer key lesson plan rubric",
    },
    {
        "tool_key": "office_mode",
        "name": "Office Mode",
        "category": "Office",
        "description": "Extract contract pages, split invoices, bulk rename files, and stamp PDFs.",
        "price_paise": 1000,
        "icon_name": "bi-briefcase",
        "template_name": "tool_pages/office_mode.html",
        "keywords": "contract invoice rename stamp",
    },
    {
        "tool_key": "ai_document_tools",
        "name": "AI Document Tools",
        "category": "AI Tools",
        "description": "Summarize, translate, extract keywords, and generate notes from documents.",
        "price_paise": 2000,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-stars",
        "template_name": "tool_pages/ai_tools.html",
        "keywords": "ai summary translate keywords notes",
    },
    {
        "tool_key": "document_templates",
        "name": "Document Templates",
        "category": "Office",
        "description": "Generate resumes, invoices, cover letters, and certificates.",
        "price_paise": 700,
        "icon_name": "bi-file-earmark-richtext",
        "template_name": "tool_pages/document_templates.html",
        "keywords": "resume invoice certificate cover letter",
    },
    {
        "tool_key": "government_office_suite",
        "name": "Government Office Suite",
        "category": "Office",
        "description": "Draft office memorandum, official letters, RTI replies, and file notes with structured output.",
        "price_paise": 2000,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-building",
        "template_name": "tool_pages/government_office_suite.html",
        "keywords": "government office memorandum rti letter file note",
    },
    {
        "tool_key": "smart_pdf_pipeline",
        "name": "Smart PDF Pipeline",
        "category": "Utilities",
        "description": "Run rotate, watermark, page numbers, compression, protection, and text extraction in one workflow.",
        "price_paise": 2400,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-diagram-3",
        "template_name": "tool_pages/smart_pipeline.html",
        "keywords": "pipeline batch automation advanced pdf workflow",
    },
    {
        "tool_key": "word_to_pdf",
        "name": "Word to PDF",
        "category": "Convert",
        "description": "Convert DOC or DOCX files into high-quality PDFs.",
        "price_paise": 700,
        "icon_name": "bi-file-earmark-word",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "word doc docx to pdf",
    },
    {
        "tool_key": "doc_to_pdf",
        "name": "DOC to PDF",
        "category": "Convert",
        "description": "Export legacy DOC files to PDF format.",
        "price_paise": 700,
        "icon_name": "bi-file-earmark-word",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "doc to pdf",
    },
    {
        "tool_key": "docx_to_pdf",
        "name": "DOCX to PDF",
        "category": "Convert",
        "description": "Create PDF output from modern DOCX documents.",
        "price_paise": 700,
        "icon_name": "bi-file-earmark-word",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "docx to pdf",
    },
    {
        "tool_key": "powerpoint_to_pdf",
        "name": "PowerPoint to PDF",
        "category": "Convert",
        "description": "Convert PPT/PPTX presentations into PDF.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-slides",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "powerpoint ppt pptx to pdf",
    },
    {
        "tool_key": "ppt_to_pdf",
        "name": "PPT to PDF",
        "category": "Convert",
        "description": "Convert PPT presentations to PDF format.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-slides",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "ppt to pdf",
    },
    {
        "tool_key": "pptx_to_pdf",
        "name": "PPTX to PDF",
        "category": "Convert",
        "description": "Convert PPTX slide decks to PDF.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-slides",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pptx to pdf",
    },
    {
        "tool_key": "excel_to_pdf",
        "name": "Excel to PDF",
        "category": "Convert",
        "description": "Convert spreadsheet files to PDF.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-excel",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "excel xls xlsx to pdf",
    },
    {
        "tool_key": "xls_to_pdf",
        "name": "XLS to PDF",
        "category": "Convert",
        "description": "Convert XLS files to PDF.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-excel",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "xls to pdf",
    },
    {
        "tool_key": "xlsx_to_pdf",
        "name": "XLSX to PDF",
        "category": "Convert",
        "description": "Convert XLSX files to PDF.",
        "price_paise": 900,
        "icon_name": "bi-file-earmark-excel",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "xlsx to pdf",
    },
    {
        "tool_key": "jpg_to_pdf",
        "name": "JPG to PDF",
        "category": "Convert",
        "description": "Turn JPG images into one PDF.",
        "price_paise": 500,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "jpg jpeg image to pdf",
    },
    {
        "tool_key": "png_to_pdf",
        "name": "PNG to PDF",
        "category": "Convert",
        "description": "Turn PNG images into one PDF.",
        "price_paise": 500,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "png image to pdf",
    },
    {
        "tool_key": "webp_to_pdf",
        "name": "WEBP to PDF",
        "category": "Convert",
        "description": "Turn WEBP images into one PDF.",
        "price_paise": 600,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "webp image to pdf",
    },
    {
        "tool_key": "heic_to_pdf",
        "name": "HEIC to PDF",
        "category": "Convert",
        "description": "Convert HEIC photos to PDF.",
        "price_paise": 700,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "heic image to pdf",
    },
    {
        "tool_key": "svg_to_pdf",
        "name": "SVG to PDF",
        "category": "Convert",
        "description": "Convert SVG graphics to PDF.",
        "price_paise": 700,
        "icon_name": "bi-filetype-svg",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "svg to pdf vector",
    },
    {
        "tool_key": "tiff_to_pdf",
        "name": "TIFF to PDF",
        "category": "Convert",
        "description": "Convert TIFF images to PDF.",
        "price_paise": 700,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "tiff tif to pdf",
    },
    {
        "tool_key": "html_to_pdf",
        "name": "HTML to PDF",
        "category": "Convert",
        "description": "Convert HTML files to PDF.",
        "price_paise": 700,
        "icon_name": "bi-filetype-html",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "html webpage to pdf",
    },
    {
        "tool_key": "text_to_pdf",
        "name": "Text to PDF",
        "category": "Convert",
        "description": "Convert text files to PDF.",
        "price_paise": 500,
        "icon_name": "bi-file-earmark-text",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "txt text to pdf",
    },
    {
        "tool_key": "pdf_to_jpg",
        "name": "PDF to JPG",
        "category": "Convert",
        "description": "Export PDF pages as JPG images.",
        "price_paise": 700,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to jpg jpeg images",
    },
    {
        "tool_key": "pdf_to_png",
        "name": "PDF to PNG",
        "category": "Convert",
        "description": "Export PDF pages as PNG images.",
        "price_paise": 700,
        "icon_name": "bi-file-image",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to png images",
    },
    {
        "tool_key": "pdf_to_docx",
        "name": "PDF to DOCX",
        "category": "Convert",
        "description": "Convert PDF content into editable DOCX.",
        "price_paise": 1000,
        "icon_name": "bi-file-earmark-word",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to docx word",
    },
    {
        "tool_key": "pdf_to_pptx",
        "name": "PDF to PPTX",
        "category": "Convert",
        "description": "Convert PDF pages into PPTX slides.",
        "price_paise": 1200,
        "icon_name": "bi-file-earmark-slides",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to pptx powerpoint",
    },
    {
        "tool_key": "pdf_to_xlsx",
        "name": "PDF to XLSX",
        "category": "Convert",
        "description": "Convert PDF data into XLSX sheet output.",
        "price_paise": 1200,
        "icon_name": "bi-file-earmark-excel",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to xlsx excel",
    },
    {
        "tool_key": "pdf_to_html",
        "name": "PDF to HTML",
        "category": "Convert",
        "description": "Export extracted PDF text into HTML format.",
        "price_paise": 700,
        "icon_name": "bi-filetype-html",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to html",
    },
    {
        "tool_key": "pdf_to_rtf",
        "name": "PDF to RTF",
        "category": "Convert",
        "description": "Export extracted PDF text into RTF format.",
        "price_paise": 700,
        "icon_name": "bi-filetype-rtf",
        "template_name": "tool_pages/conversion_suite.html",
        "keywords": "pdf to rtf",
    },
    {
        "tool_key": "extract_pages",
        "name": "Extract Pages",
        "category": "Organize",
        "description": "Extract selected pages into a new PDF.",
        "price_paise": 500,
        "icon_name": "bi-files",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "extract pages range",
    },
    {
        "tool_key": "split_by_pages",
        "name": "Split by Pages",
        "category": "Organize",
        "description": "Split PDF every N pages into separate files.",
        "price_paise": 600,
        "icon_name": "bi-distribute-vertical",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "split every n pages",
    },
    {
        "tool_key": "split_by_bookmarks",
        "name": "Split by Bookmarks",
        "category": "Organize",
        "description": "Split document using top-level bookmarks.",
        "price_paise": 700,
        "icon_name": "bi-bookmarks",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "split bookmarks",
    },
    {
        "tool_key": "split_in_half",
        "name": "Split In Half",
        "category": "Organize",
        "description": "Split a document into two equal halves.",
        "price_paise": 500,
        "icon_name": "bi-layout-split",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "split half",
    },
    {
        "tool_key": "split_by_size",
        "name": "Split by Size",
        "category": "Organize",
        "description": "Split PDF into chunks based on target file size.",
        "price_paise": 700,
        "icon_name": "bi-file-break",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "split size mb",
    },
    {
        "tool_key": "split_by_text",
        "name": "Split by Text",
        "category": "Organize",
        "description": "Create new files whenever delimiter text appears.",
        "price_paise": 700,
        "icon_name": "bi-body-text",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "split delimiter text",
    },
    {
        "tool_key": "alternate_mix_pdf",
        "name": "Alternate & Mix PDF",
        "category": "Organize",
        "description": "Mix pages from multiple PDFs in alternating order.",
        "price_paise": 700,
        "icon_name": "bi-shuffle",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "alternate mix merge",
    },
    {
        "tool_key": "crop_pdf",
        "name": "Crop PDF",
        "category": "Edit",
        "description": "Trim margins around each page.",
        "price_paise": 600,
        "icon_name": "bi-crop",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "crop margins",
    },
    {
        "tool_key": "flatten_pdf",
        "name": "Flatten PDF",
        "category": "Edit",
        "description": "Flatten PDF pages into print-ready layers.",
        "price_paise": 700,
        "icon_name": "bi-layers",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "flatten read-only",
    },
    {
        "tool_key": "grayscale_pdf",
        "name": "Grayscale PDF",
        "category": "Edit",
        "description": "Flatten PDF pages and convert output to grayscale.",
        "price_paise": 700,
        "icon_name": "bi-circle-half",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "grayscale black white",
    },
    {
        "tool_key": "extract_images_pdf",
        "name": "Extract PDF Images",
        "category": "Edit",
        "description": "Extract embedded images from PDF pages.",
        "price_paise": 700,
        "icon_name": "bi-images",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "extract images from pdf",
    },
    {
        "tool_key": "remove_annotations_pdf",
        "name": "Remove Annotations",
        "category": "Edit",
        "description": "Remove comments, highlights, and annotations.",
        "price_paise": 700,
        "icon_name": "bi-eraser",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "remove annotations highlight comments",
    },
    {
        "tool_key": "repair_pdf",
        "name": "Repair PDF",
        "category": "Utilities",
        "description": "Repair and clean malformed PDF structure.",
        "price_paise": 900,
        "icon_name": "bi-wrench-adjustable",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "repair recover pdf",
    },
    {
        "tool_key": "redact_pdf",
        "name": "Redact PDF",
        "category": "Security",
        "description": "Find and permanently black out sensitive terms.",
        "price_paise": 900,
        "icon_name": "bi-shield-x",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "redact secure privacy",
    },
    {
        "tool_key": "compare_pdf",
        "name": "Compare PDFs",
        "category": "Utilities",
        "description": "Generate textual differences between two PDFs.",
        "price_paise": 900,
        "icon_name": "bi-files-alt",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "compare diff document",
    },
    {
        "tool_key": "bates_numbering",
        "name": "Bates Numbering",
        "category": "Legal",
        "description": "Add legal-style Bates numbers to every page.",
        "price_paise": 900,
        "icon_name": "bi-123",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "bates numbering legal",
    },
    {
        "tool_key": "create_bookmarks",
        "name": "Create Bookmarks",
        "category": "Organize",
        "description": "Insert bookmark outline items into the PDF.",
        "price_paise": 700,
        "icon_name": "bi-bookmark-plus",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "create bookmarks outline",
    },
    {
        "tool_key": "edit_metadata_pdf",
        "name": "Edit Metadata",
        "category": "Utilities",
        "description": "Update title, author, subject, and keywords metadata.",
        "price_paise": 600,
        "icon_name": "bi-card-heading",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "edit metadata title author",
    },
    {
        "tool_key": "protect_pdf",
        "name": "Protect PDF",
        "category": "Security",
        "description": "Add a password to lock sensitive PDF files.",
        "price_paise": 700,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-lock",
        "template_name": "tool_pages/security.html",
        "keywords": "protect password secure",
    },
    {
        "tool_key": "unlock_pdf",
        "name": "Unlock PDF",
        "category": "Security",
        "description": "Remove password protection from PDF files.",
        "price_paise": 700,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-unlock",
        "template_name": "tool_pages/security.html",
        "keywords": "unlock remove password",
    },
    {
        "tool_key": "sign_pdf",
        "name": "Sign PDF",
        "category": "Edit",
        "description": "Place drawn or uploaded signatures on pages.",
        "price_paise": 800,
        "icon_name": "bi-vector-pen",
        "template_name": "tool_pages/signature.html",
        "keywords": "sign signature fill and sign",
    },
    {
        "tool_key": "rotate_pages",
        "name": "Rotate PDF Pages",
        "category": "Edit",
        "description": "Rotate selected PDF pages and save output.",
        "price_paise": 500,
        "icon_name": "bi-arrow-repeat",
        "template_name": "tool_pages/rotate.html",
        "keywords": "rotate pages",
    },
    {
        "tool_key": "organize_pdf",
        "name": "Organize PDF",
        "category": "Organize",
        "description": "Reorder pages using a custom sequence.",
        "price_paise": 600,
        "icon_name": "bi-layout-sidebar-inset",
        "template_name": "tool_pages/reorder.html",
        "keywords": "organize reorder pages",
    },
    {
        "tool_key": "pdf_editor",
        "name": "PDF Editor",
        "category": "Edit",
        "description": "Add text, lines, boxes, and image overlays to PDF pages.",
        "price_paise": 1200,
        "icon_name": "bi-pencil-square",
        "template_name": "tool_pages/editor_suite.html",
        "keywords": "edit pdf annotate text shape",
    },
    {
        "tool_key": "edit_pdf",
        "name": "Edit PDF",
        "category": "Edit",
        "description": "Add text, shapes, or annotations to a PDF.",
        "price_paise": 1000,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-pencil",
        "template_name": "tool_pages/editor_suite.html",
        "keywords": "quick edit annotate",
    },
    {
        "tool_key": "fill_sign_pdf",
        "name": "Fill & Sign PDF",
        "category": "Edit",
        "description": "Sign and place fields quickly for forms and approvals.",
        "price_paise": 900,
        "icon_name": "bi-pen",
        "template_name": "tool_pages/signature.html",
        "keywords": "fill sign pdf signature",
    },
    {
        "tool_key": "create_forms",
        "name": "Create Forms",
        "category": "Edit",
        "description": "Create form-like labeled fields over PDF pages.",
        "price_paise": 1100,
        "icon_name": "bi-ui-checks-grid",
        "template_name": "tool_pages/editor_suite.html",
        "keywords": "create forms pdf fields",
    },
    {
        "tool_key": "n_up_pdf",
        "name": "N-up PDF",
        "category": "Utilities",
        "description": "Place multiple PDF pages on each output sheet.",
        "price_paise": 800,
        "icon_name": "bi-grid-3x3",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "n-up pages per sheet",
    },
    {
        "tool_key": "resize_pdf",
        "name": "Resize PDF Pages",
        "category": "Edit",
        "description": "Scale page content and add custom margins.",
        "price_paise": 700,
        "icon_name": "bi-aspect-ratio",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "resize pdf margins scale",
    },
    {
        "tool_key": "deskew_pdf",
        "name": "Deskew PDF",
        "category": "OCR",
        "description": "Automatically correct tilted scanned pages.",
        "price_paise": 900,
        "icon_name": "bi-slash-square",
        "template_name": "tool_pages/advanced_pdf_ops.html",
        "keywords": "deskew straighten scanned pdf",
    },
    {
        "tool_key": "scan_to_pdf",
        "name": "Scan to PDF",
        "category": "OCR",
        "description": "Capture images and build enhanced PDF scans.",
        "price_paise": 700,
        "icon_name": "bi-camera",
        "template_name": "tool_pages/scanner.html",
        "keywords": "scan to pdf camera",
    },
    {
        "tool_key": "deskew_scan_pdf",
        "name": "Deskew Scan PDF",
        "category": "OCR",
        "description": "Scan images and auto-correct perspective for PDF output.",
        "price_paise": 900,
        "icon_name": "bi-camera-reels",
        "template_name": "tool_pages/scanner.html",
        "keywords": "deskew scan correct perspective",
    },
    {
        "tool_key": "translate_pdf",
        "name": "Translate PDF",
        "category": "AI Tools",
        "description": "Extract and translate PDF text to target language.",
        "price_paise": 1700,
        "is_subscription_only": True,
        "is_payperuse_allowed": False,
        "icon_name": "bi-translate",
        "template_name": "tool_pages/ai_tools.html",
        "keywords": "translate pdf ai",
    },
]


def seed_tool_catalog(target_total: int = 1000) -> int:
    created = 0
    existing_keys = set(db.session.execute(db.select(ToolCatalog.tool_key)).scalars().all())
    for tool_data in IMPLEMENTED_TOOLS:
        if tool_data["tool_key"] in existing_keys:
            continue
        payload = dict(tool_data)
        is_subscription_only = bool(payload.pop("is_subscription_only", False))
        is_payperuse_allowed = bool(
            payload.pop("is_payperuse_allowed", payload["price_paise"] > 0)
        )
        db.session.add(
            ToolCatalog(
                route_name="tools.tool_detail",
                is_enabled=True,
                is_subscription_only=is_subscription_only,
                is_payperuse_allowed=is_payperuse_allowed,
                **payload,
            )
        )
        existing_keys.add(tool_data["tool_key"])
        created += 1

    # Keep existing catalog entries in sync with current product definitions.
    for tool_data in IMPLEMENTED_TOOLS:
        tool = ToolCatalog.query.filter_by(tool_key=tool_data["tool_key"]).first()
        if not tool:
            continue
        payload = dict(tool_data)
        is_subscription_only = bool(payload.pop("is_subscription_only", False))
        is_payperuse_allowed = bool(
            payload.pop("is_payperuse_allowed", payload["price_paise"] > 0)
        )
        tool.name = payload["name"]
        tool.category = payload["category"]
        tool.description = payload["description"]
        tool.price_paise = payload["price_paise"]
        tool.icon_name = payload["icon_name"]
        tool.template_name = payload["template_name"]
        tool.keywords = payload["keywords"]
        tool.route_name = "tools.tool_detail"
        tool.is_enabled = True
        tool.is_subscription_only = is_subscription_only
        tool.is_payperuse_allowed = is_payperuse_allowed

    categories = [
        "Organize",
        "Convert",
        "Security",
        "Edit",
        "Students",
        "Office",
        "Legal",
        "Finance",
        "Utilities",
        "OCR",
        "AI Tools",
    ]
    category_cycle = cycle(categories)
    count = len(existing_keys)
    index = 1
    while count < target_total:
        category = next(category_cycle)
        tool_key = f"future_{category.lower().replace(' ', '_')}_{index:04d}"
        index += 1
        if tool_key in existing_keys:
            continue
        db.session.add(
            ToolCatalog(
                tool_key=tool_key,
                name=f"{category} Tool {index:04d}",
                category=category,
                description=(
                    "Placeholder catalog slot for future expansion. Admins can enable, price, "
                    "and wire this tool without schema changes."
                ),
                price_paise=500,
                is_enabled=False,
                is_subscription_only=False,
                is_payperuse_allowed=True,
                icon_name="bi-grid-3x3-gap",
                route_name="tools.tool_detail",
                template_name="tool_pages/tool_detail.html",
                keywords="future expansion catalog",
            )
        )
        existing_keys.add(tool_key)
        count += 1
        created += 1

    if not ToolCatalog.query.filter_by(is_subscription_only=True).first():
        for tool_key in (
            "ocr_pdf",
            "ai_document_tools",
            "study_pack_pro",
            "teacher_toolkit",
            "government_office_suite",
            "smart_pdf_pipeline",
        ):
            tool = ToolCatalog.query.filter_by(tool_key=tool_key).first()
            if not tool:
                continue
            tool.is_subscription_only = True
            tool.is_payperuse_allowed = False

    db.session.commit()
    return created


def seed_admin_user() -> None:
    configured_admins = (os.environ.get("ADMIN_ALLOWED_EMAILS", "") or "").strip()
    first_allowed_admin = ""
    if configured_admins:
        first_allowed_admin = next(
            (item.strip().lower() for item in configured_admins.split(",") if item.strip()),
            "",
        )
    admin_email = (
        (os.environ.get("ADMIN_SEED_EMAIL", "") or "").strip().lower()
        or first_allowed_admin
        or "admin@pdfmaster.local"
    )
    admin = User.query.filter_by(email=admin_email).first()
    if admin:
        if admin.role != "admin":
            admin.role = "admin"
            db.session.commit()
        return

    admin_password = (os.environ.get("ADMIN_SEED_PASSWORD", "") or "").strip()
    if not admin_password:
        current_app.logger.warning(
            "Admin seed skipped: set ADMIN_SEED_PASSWORD in .env to auto-create admin account."
        )
        return

    admin = User(
        full_name="Platform Admin",
        email=admin_email,
        role="admin",
        is_verified=True,
        wallet_balance_paise=500000,
    )
    admin.set_password(admin_password)
    db.session.add(admin)
    db.session.commit()
