"""initial schema

Revision ID: 28353dc72281
Revises: 
Create Date: 2026-03-08 16:03:31.899863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28353dc72281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_subscription_only', sa.Boolean(), nullable=False),
    sa.Column('is_payperuse_allowed', sa.Boolean(), nullable=False),
    sa.Column('icon_name', sa.String(length=40), nullable=False),
    sa.Column('route_name', sa.String(length=120), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=False),
    sa.Column('is_beta', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_catalog_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_catalog_tool_key'), ['tool_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('preferred_mode', sa.String(length=32), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('wallet_balance_paise', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by', sa.String(length=16), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referred_by'), ['referred_by'], unique=False)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('favorite_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tool_key', name='uq_user_tool_fav')
    )
    with op.batch_alter_table('favorite_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_tools_tool_key'), ['tool_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_tools_user_id'), ['user_id'], unique=False)

    op.create_table('managed_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storage_kind', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('managed_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_files_storage_kind'), ['storage_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_files_user_id'), ['user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('plan_key', sa.String(length=40), nullable=False),
    sa.Column('plan_name', sa.String(length=80), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=120), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=120), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('notes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_plan_key'), ['plan_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('subscription_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('delta_days', sa.Integer(), nullable=False),
    sa.Column('previous_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_ref', sa.String(length=120), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_payment_ref'), ['payment_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_key', sa.String(length=40), nullable=False),
    sa.Column('plan_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_subscriptions_plan_key'), ['plan_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('balance_after_paise', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('input_filename', sa.String(length=255), nullable=False),
    sa.Column('output_filename', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_output_file_id'), ['output_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tool_key'), ['tool_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_links_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_share_links_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_share_links_token'))
        batch_op.drop_index(batch_op.f('ix_share_links_file_id'))

    op.drop_table('share_links')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_tool_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_output_file_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_transaction_type'))

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_user_subscriptions_plan_key'))

    op.drop_table('user_subscriptions')
    with op.batch_alter_table('subscription_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_source'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_payment_ref'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_subscription_events_actor_id'))

    op.drop_table('subscription_events')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_plan_key'))

    op.drop_table('payments')
    with op.batch_alter_table('managed_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_managed_files_storage_kind'))

    op.drop_table('managed_files')
    with op.batch_alter_table('favorite_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_tools_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorite_tools_tool_key'))

    op.drop_table('favorite_tools')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_action'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referred_by'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tool_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_catalog_tool_key'))
        batch_op.drop_index(batch_op.f('ix_tool_catalog_category'))

    op.drop_table('tool_catalog')
    # ### end Alembic commands ###
