"""advanced workspace features

Revision ID: 49b261cbdeef
Revises: 28353dc72281
Create Date: 2026-03-08 16:33:26.314013

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '49b261cbdeef'
down_revision = '28353dc72281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('key_prefix', name='uq_api_key_prefix')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('cloud_integration_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('account_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_cloud_connection_user_provider')
    )
    with op.batch_alter_table('cloud_integration_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_integration_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_integration_connections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_integration_connections_user_id'), ['user_id'], unique=False)

    op.create_table('document_version_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_version_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_version_groups_user_id'), ['user_id'], unique=False)

    op.create_table('privacy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_delete_hours', sa.Integer(), nullable=False),
    sa.Column('private_mode_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_share_links', sa.Boolean(), nullable=False),
    sa.Column('keep_download_history', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_privacy_setting_user')
    )
    with op.batch_alter_table('privacy_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_settings_user_id'), ['user_id'], unique=False)

    op.create_table('team_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_workspaces_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspaces_status'), ['status'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=120), nullable=False),
    sa.Column('event_types_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_user_id'), ['user_id'], unique=False)

    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_ms', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_logs_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_usage_logs_user_id'), ['user_id'], unique=False)

    op.create_table('bulk_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tool_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('failed_files', sa.Integer(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_archive_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_archive_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_batches_output_archive_file_id'), ['output_archive_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batches_tool_key'), ['tool_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batches_user_id'), ['user_id'], unique=False)

    op.create_table('cloud_transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('target_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['target_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cloud_transfer_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_target_file_id'), ['target_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cloud_transfer_logs_user_id'), ['user_id'], unique=False)

    op.create_table('compliance_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['output_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_reports_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_output_file_id'), ['output_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_reports_user_id'), ['user_id'], unique=False)

    op.create_table('document_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extraction_strategy', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chat_sessions_source_file_id'), ['source_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chat_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chat_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['document_version_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_versions_group_id'), ['group_id'], unique=False)

    op.create_table('file_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_access_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_access_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_access_logs_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_access_logs_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('form_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('share_token', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['managed_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_templates_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_templates_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_form_templates_source_file_id'), ['source_file_id'], unique=False)

    op.create_table('signature_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('signed_file_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('access_token', sa.String(length=120), nullable=False),
    sa.Column('signer_order_enforced', sa.Boolean(), nullable=False),
    sa.Column('current_order', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_file_id'], ['managed_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_requests_access_token'), ['access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_signature_requests_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_signed_file_id'), ['signed_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_requests_status'), ['status'], unique=False)

    op.create_table('team_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['team_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_activities_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_activities_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_activities_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('team_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['team_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_projects_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_projects_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('team_workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['team_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email', name='uq_workspace_member_email')
    )
    with op.batch_alter_table('team_workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_workspace_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspace_members_invited_by_user_id'), ['invited_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspace_members_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspace_members_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_event_name'), ['event_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_success'), ['success'], unique=False)

    op.create_table('bulk_batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('input_file_id', sa.Integer(), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('log_message', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['bulk_batches.id'], ),
    sa.ForeignKeyConstraint(['input_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['output_file_id'], ['managed_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_batch_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batch_items_input_file_id'), ['input_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batch_items_output_file_id'), ['output_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_batch_items_status'), ['status'], unique=False)

    op.create_table('document_chat_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['document_chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chat_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chat_chunks_page_number'), ['page_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chat_chunks_session_id'), ['session_id'], unique=False)

    op.create_table('document_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['document_chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chat_messages_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('document_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_a_id', sa.Integer(), nullable=False),
    sa.Column('version_b_id', sa.Integer(), nullable=False),
    sa.Column('report_file_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('diff_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_a_id'], ['document_versions.id'], ),
    sa.ForeignKeyConstraint(['version_b_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_comparisons_report_file_id'), ['report_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_version_a_id'), ['version_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_comparisons_version_b_id'), ['version_b_id'], unique=False)

    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('output_file_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('values_json', sa.JSON(), nullable=False),
    sa.Column('submit_token', sa.String(length=120), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_submissions_output_file_id'), ['output_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_submit_token'), ['submit_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_form_submissions_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_submissions_template_id'), ['template_id'], unique=False)

    op.create_table('form_template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['form_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_template_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_form_template_fields_field_type'), ['field_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_form_template_fields_template_id'), ['template_id'], unique=False)

    op.create_table('share_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_link_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_access_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_access_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_access_logs_share_link_id'), ['share_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_access_logs_status'), ['status'], unique=False)

    op.create_table('signature_signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('signer_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_code', sa.String(length=12), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'email', name='uq_signature_signer_request_email')
    )
    with op.batch_alter_table('signature_signers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_signers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_signers_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_signers_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_signers_user_id'), ['user_id'], unique=False)

    op.create_table('team_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['team_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_comments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_comments_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_comments_user_id'), ['user_id'], unique=False)

    op.create_table('team_project_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['managed_files.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['team_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_project_files_added_by_user_id'), ['added_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_project_files_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_project_files_project_id'), ['project_id'], unique=False)

    op.create_table('signature_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['signature_signers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_events_signer_id'), ['signer_id'], unique=False)

    op.create_table('signature_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signature_requests.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['signature_signers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signature_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signature_fields_field_type'), ['field_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_fields_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signature_fields_signer_id'), ['signer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signature_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_fields_signer_id'))
        batch_op.drop_index(batch_op.f('ix_signature_fields_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_fields_field_type'))

    op.drop_table('signature_fields')
    with op.batch_alter_table('signature_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_events_signer_id'))
        batch_op.drop_index(batch_op.f('ix_signature_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_events_event_type'))

    op.drop_table('signature_events')
    with op.batch_alter_table('team_project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_project_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_team_project_files_file_id'))
        batch_op.drop_index(batch_op.f('ix_team_project_files_added_by_user_id'))

    op.drop_table('team_project_files')
    with op.batch_alter_table('team_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_comments_target_type'))
        batch_op.drop_index(batch_op.f('ix_team_comments_project_id'))

    op.drop_table('team_comments')
    with op.batch_alter_table('signature_signers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_signers_user_id'))
        batch_op.drop_index(batch_op.f('ix_signature_signers_status'))
        batch_op.drop_index(batch_op.f('ix_signature_signers_request_id'))
        batch_op.drop_index(batch_op.f('ix_signature_signers_email'))

    op.drop_table('signature_signers')
    with op.batch_alter_table('share_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_access_logs_status'))
        batch_op.drop_index(batch_op.f('ix_share_access_logs_share_link_id'))
        batch_op.drop_index(batch_op.f('ix_share_access_logs_event'))

    op.drop_table('share_access_logs')
    with op.batch_alter_table('form_template_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_template_fields_template_id'))
        batch_op.drop_index(batch_op.f('ix_form_template_fields_field_type'))

    op.drop_table('form_template_fields')
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_submissions_template_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_submit_token'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_form_submissions_output_file_id'))

    op.drop_table('form_submissions')
    with op.batch_alter_table('document_comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_comparisons_version_b_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_version_a_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_comparisons_report_file_id'))

    op.drop_table('document_comparisons')
    with op.batch_alter_table('document_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_document_chat_messages_role'))

    op.drop_table('document_chat_messages')
    with op.batch_alter_table('document_chat_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chat_chunks_session_id'))
        batch_op.drop_index(batch_op.f('ix_document_chat_chunks_page_number'))

    op.drop_table('document_chat_chunks')
    with op.batch_alter_table('bulk_batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_batch_items_status'))
        batch_op.drop_index(batch_op.f('ix_bulk_batch_items_output_file_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_batch_items_input_file_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_batch_items_batch_id'))

    op.drop_table('bulk_batch_items')
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_success'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_event_name'))
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_endpoint_id'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('team_workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_status'))
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_role'))
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_invited_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_workspace_members_email'))

    op.drop_table('team_workspace_members')
    with op.batch_alter_table('team_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_projects_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_team_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_team_projects_approval_status'))

    op.drop_table('team_projects')
    with op.batch_alter_table('team_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_activities_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_team_activities_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_activities_action'))

    op.drop_table('team_activities')
    with op.batch_alter_table('signature_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signature_requests_status'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_signed_file_id'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_file_id'))
        batch_op.drop_index(batch_op.f('ix_signature_requests_access_token'))

    op.drop_table('signature_requests')
    with op.batch_alter_table('form_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_form_templates_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_form_templates_share_token'))
        batch_op.drop_index(batch_op.f('ix_form_templates_owner_id'))

    op.drop_table('form_templates')
    with op.batch_alter_table('file_access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_access_logs_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_access_logs_file_id'))
        batch_op.drop_index(batch_op.f('ix_file_access_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_file_access_logs_action'))

    op.drop_table('file_access_logs')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_group_id'))
        batch_op.drop_index(batch_op.f('ix_document_versions_file_id'))

    op.drop_table('document_versions')
    with op.batch_alter_table('document_chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_chat_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_document_chat_sessions_source_file_id'))

    op.drop_table('document_chat_sessions')
    with op.batch_alter_table('compliance_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_output_file_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_reports_file_id'))

    op.drop_table('compliance_reports')
    with op.batch_alter_table('cloud_transfer_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_target_file_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_status'))
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_source_file_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_cloud_transfer_logs_direction'))

    op.drop_table('cloud_transfer_logs')
    with op.batch_alter_table('bulk_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_batches_user_id'))
        batch_op.drop_index(batch_op.f('ix_bulk_batches_tool_key'))
        batch_op.drop_index(batch_op.f('ix_bulk_batches_status'))
        batch_op.drop_index(batch_op.f('ix_bulk_batches_output_archive_file_id'))

    op.drop_table('bulk_batches')
    with op.batch_alter_table('api_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_endpoint'))
        batch_op.drop_index(batch_op.f('ix_api_usage_logs_api_key_id'))

    op.drop_table('api_usage_logs')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_user_id'))
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_is_active'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('team_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_workspaces_status'))
        batch_op.drop_index(batch_op.f('ix_team_workspaces_owner_id'))

    op.drop_table('team_workspaces')
    with op.batch_alter_table('privacy_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_settings_user_id'))

    op.drop_table('privacy_settings')
    with op.batch_alter_table('document_version_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_version_groups_user_id'))

    op.drop_table('document_version_groups')
    with op.batch_alter_table('cloud_integration_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cloud_integration_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_cloud_integration_connections_status'))
        batch_op.drop_index(batch_op.f('ix_cloud_integration_connections_provider'))

    op.drop_table('cloud_integration_connections')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_is_active'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
